//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba3
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntregaPedidos
    {
        public int IdEntrega { get; set; }
        public int IdPedido { get; set; }
        public int IdEmpleado { get; set; }
        public int CantidadTotal { get; set; }
        public string Direccion { get; set; }
        public string FormaEntrega { get; set; }
        public decimal PresioTotal { get; set; }
        public System.DateTime FechaEntrega { get; set; }
    }
}
